name: Deploy Pizzeria App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Ambil Kode Terbaru
        uses: actions/checkout@v3

      - name: Matikan Container Lama (Jika Ada)
        run: docker compose down || true

      - name: Bangun Ulang Container
        run: docker compose up -d --build

      - name: Cek Status
        run: docker psname: Hello World Workflow
on:
  push:
    branches: [ main ]
jobs:
  greeting:
    runs-on: [self-hosted]
    steps:
      - name: Say Hello
        run: echo "Hello, World! Berhasil connect!"
